name: dartdev
description: A unified tool for Dart development.
version: 0.0.1
homepage: https://github.com/devoncarew/dartdev
author: Devon Carew <devoncarew@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analysis_server_lib: ^0.1.1+1
  args: ^1.4.0
  cli_util: ^0.1.0
  intl: ^0.16.0
  path: ^1.4.0
  stagehand: any
  watcher: ^0.9.0
  yaml: ^2.0.0

dev_dependencies:
  test: any
